module.exports = {
  apps: [
    {
      name: 'ankrshield-web',
      script: 'npx',
      args: 'vite preview --port 5250 --host 0.0.0.0',
      cwd: '/root/ankrshield/apps/web',
      env: {
        NODE_ENV: 'production',
        VITE_API_URL: 'http://localhost:4250',
        VITE_WS_URL: 'ws://localhost:4250',
      },
      error_file: '/root/.pm2/logs/ankrshield-web-error.log',
      out_file: '/root/.pm2/logs/ankrshield-web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
    },
    {
      name: 'ankrshield-api',
      script: 'npx',
      args: 'tsx src/main.ts',
      cwd: '/root/ankrshield/apps/api',
      env: {
        PORT: '4250',
        DATABASE_URL: 'postgresql://ankrshield:ankrshield123@localhost:5432/ankrshield',
        REDIS_URL: 'redis://localhost:6379',
        JWT_SECRET: 'ankrshield-jwt-secret-change-in-production',
        NODE_ENV: 'development',
        CORS_ORIGIN: 'http://localhost:5250,https://ankr.digital',
        // AI Warrior
        ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY || '',
        WARRIOR_MODEL: 'claude-sonnet-4-6',
        WARRIOR_CORRELATION_WINDOW_MS: '300000',
        WARRIOR_THREAT_THRESHOLD: '55',
        WARRIOR_AUTO_QUARANTINE_SCORE: '88',
        WARRIOR_ENABLE_HONEYPOTS: 'true',
        WARRIOR_REPORT_INTERVAL_MS: '86400000',
        WARRIOR_SPYWARE_SCAN_INTERVAL_MS: '21600000',
        DEFAULT_WORKSPACE_ROOT: process.env.DEFAULT_WORKSPACE_ROOT || '',
        // AnkrWire
        ANKR_WIRE_WS_URL: 'http://localhost:4007',
        ANKR_WIRE_URL: 'http://localhost:4007',
      },
      error_file: '/root/.pm2/logs/ankrshield-api-error.log',
      out_file: '/root/.pm2/logs/ankrshield-api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
    },
  ],
};
