/**
 * TAXII 2.1 Server (X11)
 *
 * Implements the TAXII 2.1 specification over Fastify.
 * All responses use Content-Type: application/taxii+json;version=2.1
 *
 * Routes:
 *   GET /taxii/                         — Discovery endpoint
 *   GET /taxii/api/                     — API root info
 *   GET /taxii/api/collections/         — List collections
 *   GET /taxii/api/collections/xshield-ioc/objects/
 *       ?domain=example.com             — run scan, return STIX bundle
 *       ?limit=100&minScore=60          — return cached high-risk domain STIX indicators
 *
 * Authentication: PRO tier API key via X-API-Key header (for the objects endpoint).
 *
 * Reference: https://docs.oasis-open.org/cti/taxii/v2.1/os/taxii-v2.1-os.html
 */

import { createHash } from 'crypto';

import { runRiskEngine } from '@ankrshield/risk-intelligence';
import type { FastifyInstance } from 'fastify';

import { buildStixBundle } from './stix-builder.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const TAXII_MEDIA_TYPE = 'application/taxii+json;version=2.1';
const API_ROOT_PATH = '/taxii/api/';
const COLLECTION_ID = 'xshield-ioc';

// ---------------------------------------------------------------------------
// Auth helpers
// ---------------------------------------------------------------------------

function hashKey(raw: string): string {
  return createHash('sha256').update(raw).digest('hex');
}

async function resolveApiKeyRecord(
  rawKey: string,
  prisma: any
): Promise<{ tier: string; isActive: boolean } | null> {
  try {
    const hash = hashKey(rawKey);
    return await prisma.xShieldApiKey.findUnique({ where: { keyHash: hash } });
  } catch {
    return null;
  }
}

async function requireProKey(request: any, reply: any, prisma: any): Promise<boolean> {
  const rawKey =
    (request.headers['x-api-key'] as string) ??
    request.headers.authorization?.replace('Bearer ', '');

  if (!rawKey) {
    reply
      .status(401)
      .header('Content-Type', TAXII_MEDIA_TYPE)
      .send({ title: 'Unauthorized', description: 'X-API-Key header required', http_status: 401 });
    return false;
  }

  const key = await resolveApiKeyRecord(rawKey, prisma);
  if (!key || !key.isActive) {
    reply.status(401).header('Content-Type', TAXII_MEDIA_TYPE).send({
      title: 'Unauthorized',
      description: 'Invalid or inactive API key',
      http_status: 401,
    });
    return false;
  }

  if (key.tier !== 'PRO' && key.tier !== 'ENTERPRISE') {
    reply.status(403).header('Content-Type', TAXII_MEDIA_TYPE).send({
      title: 'Forbidden',
      description:
        'TAXII endpoint requires a PRO or ENTERPRISE API key. Upgrade at xshieldai.com/pricing',
      http_status: 403,
    });
    return false;
  }

  return true;
}

// ---------------------------------------------------------------------------
// Plugin registration
// ---------------------------------------------------------------------------

export async function registerTaxiiRoutes(fastify: FastifyInstance, prisma: any): Promise<void> {
  // ── Discovery endpoint ────────────────────────────────────────────────────
  fastify.get('/taxii/', async (_request, reply) => {
    return reply.header('Content-Type', TAXII_MEDIA_TYPE).send({
      title: 'xShield TAXII 2.1 Server',
      description:
        'TAXII 2.1 server exposing STIX 2.1 threat intelligence bundles generated by xShield Risk Intelligence.',
      contact: 'security@xshieldai.com',
      default: API_ROOT_PATH,
      api_roots: [API_ROOT_PATH],
    });
  });

  // ── API root info ─────────────────────────────────────────────────────────
  fastify.get('/taxii/api/', async (_request, reply) => {
    return reply.header('Content-Type', TAXII_MEDIA_TYPE).send({
      title: 'xShield IOC API Root',
      description:
        'Primary API root providing access to xShield-generated STIX 2.1 Indicators of Compromise.',
      versions: ['application/taxii+json;version=2.1'],
      max_content_length: 10_485_760, // 10 MB
    });
  });

  // ── Collection listing ────────────────────────────────────────────────────
  fastify.get('/taxii/api/collections/', async (_request, reply) => {
    return reply.header('Content-Type', TAXII_MEDIA_TYPE).send({
      collections: [
        {
          id: COLLECTION_ID,
          title: 'xShield IOC Feed',
          description:
            'STIX 2.1 Indicator and Threat Actor objects derived from xShield risk scans. ' +
            'Includes domain-name indicators, attack-patterns (MITRE ATT&CK), ' +
            'threat-actors (when risk >= HIGH), and courses-of-action.',
          can_read: true,
          can_write: true,
          media_types: [TAXII_MEDIA_TYPE],
        },
      ],
    });
  });

  // ── Objects endpoint ──────────────────────────────────────────────────────
  // GET /taxii/api/collections/xshield-ioc/objects/
  //   ?domain=example.com  — scan on-demand, return STIX bundle
  //   ?limit=N&minScore=N  — return cached recent high-risk reports as STIX
  fastify.get<{
    Querystring: { domain?: string; limit?: string; minScore?: string };
  }>('/taxii/api/collections/xshield-ioc/objects/', async (request, reply) => {
    // Require PRO API key
    const authed = await requireProKey(request, reply, prisma);
    if (!authed) return;

    const { domain, limit, minScore } = request.query;
    const limitN = Math.min(parseInt(limit ?? '100', 10) || 100, 500);
    const minScoreN = parseInt(minScore ?? '60', 10) || 60;

    // ── Mode A: on-demand domain scan ──────────────────────────────────────
    if (domain?.trim()) {
      const cleanDomain = domain.trim().toLowerCase();
      try {
        const report = await runRiskEngine({
          domain: cleanDomain,
          enableThreatNarrative: false, // skip AI narrative for TAXII (speed)
        });
        const bundle = buildStixBundle(report as any);
        return reply
          .status(200)
          .header('Content-Type', TAXII_MEDIA_TYPE)
          .header('X-TAXII-Date-Added-First', report.generatedAt)
          .header('X-TAXII-Date-Added-Last', report.generatedAt)
          .send({
            more: false,
            next: null,
            objects: bundle.objects,
          });
      } catch (err: unknown) {
        return reply
          .status(500)
          .header('Content-Type', TAXII_MEDIA_TYPE)
          .send({
            title: 'Internal Error',
            description: err instanceof Error ? err.message : String(err),
            http_status: 500,
          });
      }
    }

    // ── Mode B: cached recent high-risk domains from DB ───────────────────
    try {
      const reports = await prisma.xShieldRiskReport.findMany({
        where: {
          riskScore: { gte: minScoreN },
          createdAt: { gte: new Date(Date.now() - 7 * 24 * 3600 * 1000) }, // last 7 days
        },
        orderBy: { riskScore: 'desc' },
        take: limitN,
        distinct: ['domain'],
        select: {
          id: true,
          domain: true,
          riskScore: true,
          riskLevel: true,
          createdAt: true,
          findings: true,
          mitreMapping: true,
        },
      });

      // Build a synthetic RiskReport-compatible object for each DB record
      const allObjects: object[] = [];
      let dateAddedFirst: string | null = null;
      let dateAddedLast: string | null = null;

      for (const r of reports) {
        const ts = (r.createdAt as Date).toISOString();
        if (!dateAddedFirst) dateAddedFirst = ts;
        dateAddedLast = ts;

        const syntheticReport = {
          id: r.id as string,
          domain: r.domain as string,
          riskScore: r.riskScore as number,
          riskLevel: ((r.riskLevel as string) || 'medium').toLowerCase() as any,
          generatedAt: ts,
          serverIp: null,
          factors: Array.isArray(r.findings) ? (r.findings as any[]) : [],
          greynoise: null,
          exposedServices: [],
          breaches: [],
          domainThreats: [],
          otx: null,
          suspiciousCerts: [],
          registeredTyposquats: [],
          pasteHits: [],
          dnsSecurityReport: null,
          phishingHits: [],
          asnRecord: null,
          githubLeaks: [],
          ransomwareResult: null,
          canaryResult: null,
          entropyReports: null,
          qrResult: null,
          exfilResults: [],
          socialC2Result: null,
          brandFindings: null,
          threatNarrative: null,
          durationMs: 0,
          // Spread MITRE data if stored
          mitreMapping: (r.mitreMapping as any)?.mappings ?? [],
          recommendations: (r.mitreMapping as any)?.recommendations ?? [],
        };

        const bundle = buildStixBundle(syntheticReport as any);
        allObjects.push(...bundle.objects);
      }

      return reply
        .status(200)
        .header('Content-Type', TAXII_MEDIA_TYPE)
        .header('X-TAXII-Date-Added-First', dateAddedFirst ?? new Date().toISOString())
        .header('X-TAXII-Date-Added-Last', dateAddedLast ?? new Date().toISOString())
        .send({
          more: reports.length === limitN,
          next: reports.length === limitN ? String(limitN) : null,
          objects: allObjects,
        });
    } catch (err: unknown) {
      return reply
        .status(500)
        .header('Content-Type', TAXII_MEDIA_TYPE)
        .send({
          title: 'Internal Error',
          description: err instanceof Error ? err.message : String(err),
          http_status: 500,
        });
    }
  });

  // ── TAXII Write endpoint ──────────────────────────────────────────────────
  // POST /taxii/api/collections/xshield-ioc/objects/
  // Accepts STIX 2.1 bundle from external producers (xshield-active beacon push,
  // OT sensors, partner feeds). Validates envelope, stores raw bundle, returns status.
  // @rule:XSACT-008 — beacon STIX push lands here
  // @rule:CA-003 — response carries before/after state
  fastify.post<{
    Body: {
      type: string;
      id?: string;
      spec_version?: string;
      objects: Array<{ type: string; id: string; [key: string]: unknown }>;
    };
  }>('/taxii/api/collections/xshield-ioc/objects/', async (request, reply) => {
    const authed = await requireProKey(request, reply, prisma);
    if (!authed) return;

    const start = Date.now();
    const bundle = request.body;

    // Validate STIX 2.1 envelope
    if (bundle.type !== 'bundle' || !Array.isArray(bundle.objects) || bundle.objects.length === 0) {
      return reply.status(400).header('Content-Type', TAXII_MEDIA_TYPE).send({
        title: 'Invalid Bundle',
        description: 'Body must be a STIX 2.1 bundle with type="bundle" and at least one object.',
        http_status: 400,
      });
    }

    // Extract known object types from incoming bundle
    const indicators = bundle.objects.filter((o) => o.type === 'indicator');
    const threatActors = bundle.objects.filter((o) => o.type === 'threat-actor');
    const before_snapshot = { objects_in_collection: await prisma.xShieldRiskReport.count() };

    // Persist each indicator as a lightweight risk report stub
    // Full OT sensor integration (Phase 8): dedicated TaxiiIngest model
    const stored: string[] = [];
    for (const indicator of indicators) {
      const domain = extractDomainFromPattern((indicator.pattern as string) ?? '');
      if (!domain) continue;

      try {
        await prisma.xShieldRiskReport.upsert({
          where: { domain },
          create: {
            domain,
            riskScore: 75, // external indicator default — not xShield-scanned
            riskLevel: 'HIGH',
            source: 'taxii_ingest',
            rawBundle: JSON.stringify(bundle),
            generatedAt: new Date().toISOString(),
          },
          update: {
            source: 'taxii_ingest',
            rawBundle: JSON.stringify(bundle),
            generatedAt: new Date().toISOString(),
          },
        });
        stored.push(domain);
      } catch (_e) {
        // Non-blocking — log and continue
        fastify.log.warn({ domain }, '[taxii-ingest] upsert failed — skipped');
      }
    }

    const after_snapshot = {
      objects_in_collection: before_snapshot.objects_in_collection + stored.length,
    };

    return reply
      .status(200)
      .header('Content-Type', TAXII_MEDIA_TYPE)
      .send({
        id: `status--${Date.now()}`,
        status: 'complete',
        request_timestamp: new Date().toISOString(),
        total_count: bundle.objects.length,
        success_count: stored.length,
        failure_count: indicators.length - stored.length,
        pending_count: 0,
        successes: stored.map((d) => ({
          id: d,
          version: new Date().toISOString(),
          message: 'ingested',
        })),
        // @rule:CA-003 before/after state in response
        before_snapshot,
        after_snapshot,
        delta: { indicators_added: stored.length, threat_actors_seen: threatActors.length },
        _meta: {
          computed_at: new Date().toISOString(),
          duration_ms: Date.now() - start,
          trust_mask_applied: 1,
        },
      });
  });

  fastify.log.info(
    'TAXII 2.1 routes registered: /taxii/, /taxii/api/, /taxii/api/collections/xshield-ioc/objects/ (GET + POST)'
  );
}

// ── Helpers ─────────────────────────────────────────────────────────────────

/** Extract domain from STIX indicator pattern like [domain-name:value = 'evil.com'] */
function extractDomainFromPattern(pattern: string): string | null {
  const match = pattern?.match(/domain-name:value\s*=\s*'([^']+)'/i);
  return match?.[1] ?? null;
}
