/**
 * @ankrshield/ai-warrior — Core Types
 *
 * All domain types for the AI Warrior threat intelligence engine.
 */

// ─── Severity & Source ──────────────────────────────────────────────────────

export type ThreatSeverity = 'info' | 'low' | 'warning' | 'high' | 'critical';

export type ThreatSource =
  | 'ai-agent'
  | 'network'
  | 'file-system'
  | 'clipboard'
  | 'dns'
  | 'process'
  | 'honeypot';

// ─── Threat Event ─────────────────────────────────────────────────────────────
// The primitive unit ingested by the warrior. Produced from AI activities,
// network flows, file system hooks, DNS events, etc.

export interface ThreatEvent {
  id: string;
  timestamp: Date;
  source: ThreatSource;
  severity: ThreatSeverity;

  // Attribution
  agentId?: string;
  agentName?: string;

  // What happened
  action: string;       // e.g. "FILE_READ", "NETWORK_UPLOAD", "CLIPBOARD_ACCESS"
  resource: string;     // e.g. file path, domain, endpoint

  // Size (bytes transferred, file size, etc.)
  byteCount?: number;

  // Arbitrary extra context
  metadata: Record<string, unknown>;

  // Was it already blocked by another layer?
  isBlocked: boolean;
  blockReason?: string;
}

// ─── Attack Types ────────────────────────────────────────────────────────────

export type AttackType =
  | 'data_exfiltration'
  | 'credential_theft'
  | 'lateral_movement'
  | 'ransomware'
  | 'surveillance'
  | 'supply_chain_compromise'
  | 'privilege_escalation'
  | 'honeypot_triggered'
  | 'unknown';

// ─── Attack Chain ─────────────────────────────────────────────────────────────
// A correlated group of ThreatEvents forming a single attack narrative.

export interface AttackChain {
  id: string;
  detectedAt: Date;
  startTime: Date;
  endTime: Date;

  // Correlated events
  events: ThreatEvent[];

  // Classification
  attackType: AttackType;
  threatScore: number;          // 0–100

  // LLM-generated descriptions
  narrative: string;            // Plain English for non-technical users
  technicalSummary: string;     // Technical analysis for security teams

  // Impact
  affectedAssets: string[];     // File paths, domains, credentials affected

  // Response
  suggestedActions: string[];   // Human-readable remediation steps
  autoActionsApplied: string[]; // Actions already taken automatically
}

// ─── Generated Policy ─────────────────────────────────────────────────────────
// A policy rule set auto-generated by the warrior in response to an attack chain.

export type PolicyRuleType =
  | 'deny_file_path'
  | 'deny_domain'
  | 'deny_file_type'
  | 'cap_upload_bytes'
  | 'require_confirmation'
  | 'quarantine_agent'
  | 'block_clipboard';

export interface GeneratedPolicyRule {
  type: PolicyRuleType;
  value: string;        // The path / domain / type / bytes cap
  reason: string;       // Why this rule was generated
}

export interface GeneratedPolicy {
  id: string;
  name: string;
  description: string;
  triggeredBy: string;           // AttackChain.id
  rules: GeneratedPolicyRule[];
  confidence: number;            // 0–100 — how certain the LLM is
  autoApplied: boolean;
  requiresApproval: boolean;
  createdAt: Date;
}

// ─── Honeypot ─────────────────────────────────────────────────────────────────
// Decoy assets placed on the file system to detect malicious intent.

export type HoneypotType = 'file' | 'directory' | 'api-key' | 'wallet' | 'credential';

export interface HoneypotAsset {
  id: string;
  type: HoneypotType;
  path: string;
  name: string;
  content: string;      // The decoy content placed in the file
  createdAt: Date;
  lastCheckedAtime: number; // ms — atime snapshot at last poll

  // Trigger state
  triggered: boolean;
  triggeredAt?: Date;
  triggeredAgentId?: string;
}

// ─── Quarantine ───────────────────────────────────────────────────────────────

export interface QuarantinedAgent {
  agentId: string;
  agentName: string;
  quarantinedAt: Date;
  reason: string;
  attackChainId: string;
  isActive: boolean;    // still quarantined vs. released
}

// ─── Incident Report ──────────────────────────────────────────────────────────

export interface TimelineEntry {
  timestamp: Date;
  severity: ThreatSeverity;
  event: string;
  agentName?: string;
  resource?: string;
}

export interface IncidentReport {
  id: string;
  generatedAt: Date;
  period: { start: Date; end: Date };

  // Scores
  riskScore: number;             // 0–100 overall

  // LLM-generated summaries
  executiveSummary: string;      // 2–3 sentence plain English
  technicalAnalysis: string;     // Full technical breakdown

  // Data
  attackChains: AttackChain[];
  honeypotTriggers: HoneypotAsset[];
  policiesGenerated: GeneratedPolicy[];
  quarantinedAgents: QuarantinedAgent[];

  // Rolled-up insights
  topThreats: string[];
  recommendations: string[];
  timeline: TimelineEntry[];

  // Stats
  totalEventsAnalyzed: number;
  totalAlertsGenerated: number;
}

// ─── Warrior Config ───────────────────────────────────────────────────────────

export interface WarriorConfig {
  // LLM
  anthropicApiKey: string;
  model?: string;                    // Default: claude-sonnet-4-6

  // Correlation tuning
  correlationWindowMs?: number;      // Default: 5 minutes (300_000)
  minEventsForChain?: number;        // Default: 2
  threatScoreThreshold?: number;     // Default: 55 — trigger policy gen

  // Response automation
  autoApplyPolicies?: boolean;       // Default: false — require user approval
  autoQuarantineScore?: number;      // Default: 88 — auto-quarantine above this

  // Honeypots
  enableHoneypots?: boolean;         // Default: true
  honeypotDirectory?: string;        // Default: os.tmpdir()/ankrshield-honeypots
  honeypotPollIntervalMs?: number;   // Default: 30_000

  // Reporting
  reportIntervalMs?: number;         // Default: 86_400_000 (24 hours)

  // Buffer cap
  maxEventBufferSize?: number;       // Default: 10_000
}

// Internal: all fields required (after applying defaults)
export type ResolvedWarriorConfig = Required<WarriorConfig>;

// ─── Warrior Status ───────────────────────────────────────────────────────────

export interface WarriorStatus {
  isRunning: boolean;
  eventsIngested: number;
  attackChainsDetected: number;
  policiesGenerated: number;
  honeypotTriggers: number;
  quarantinedAgents: number;
  scopeViolations: number;
  lastReportAt?: Date;
  uptimeMs: number;
}

// ─── LLM Narration Response ───────────────────────────────────────────────────
// What the LLM returns for a threat narration request.

export interface NarrationResult {
  narrative: string;
  technicalSummary: string;
  severity: ThreatSeverity;
  attackType: AttackType;
  affectedAssets: string[];
  suggestedActions: string[];
}

// ─── LLM Policy Response ──────────────────────────────────────────────────────

export interface PolicySuggestion {
  name: string;
  description: string;
  rules: GeneratedPolicyRule[];
  confidence: number;
  requiresApproval: boolean;
}

// ─── Reporter Input ───────────────────────────────────────────────────────────

export interface ReporterInput {
  period: { start: Date; end: Date };
  attackChains: AttackChain[];
  honeypotTriggers: HoneypotAsset[];
  policiesGenerated: GeneratedPolicy[];
  quarantinedAgents: QuarantinedAgent[];
  totalEventsAnalyzed: number;
}

// ─── Re-exports from ScopeEnforcer ───────────────────────────────────────────
// Kept here so consumers can import everything from a single types barrel.

export type {
  AgentScopeContract,
  ScopeViolation,
  ScopeViolationType,
  ScopeViolationAction,
  BuiltinPresetId,
} from './defense/scope-enforcer';
