/**
 * AI Warrior GraphQL Resolvers
 *
 * Queries:  warriorStatus, attackChains, scopeViolations, generatedPolicies,
 *           quarantinedAgents, honeypotAssets, warriorEvents, incidentReport
 *
 * Mutations: releaseAgent, ingestThreatEvent, registerScopePreset,
 *            addHoneypot, deployDefaultHoneypots
 */

import { builder } from '../builder';
import {
  getWarrior,
  getRecentEvents,
} from '../../warrior/warrior-service';
import type { ThreatSource, ThreatSeverity } from '@ankrshield/ai-warrior';

// ─── Queries ──────────────────────────────────────────────────────────────────

builder.queryField('warriorStatus', (t) =>
  t.field({
    type: 'WarriorStatus',
    description: 'Current runtime status of the AI Warrior engine.',
    resolve: () => getWarrior().getStatus(),
  })
);

builder.queryField('attackChains', (t) =>
  t.field({
    type: ['AttackChain'],
    description: 'All correlated attack chains detected in the current session.',
    args: {
      limit: t.arg.int({ defaultValue: 50 }),
      minThreatScore: t.arg.float({ defaultValue: 0 }),
    },
    resolve: (_p, args) => {
      const chains = getWarrior().getAttackChains();
      return chains
        .filter((c) => c.threatScore >= (args.minThreatScore ?? 0))
        .slice(0, args.limit ?? 50);
    },
  })
);

builder.queryField('scopeViolations', (t) =>
  t.field({
    type: ['WarriorScopeViolation'],
    description: 'Scope violations detected for all or a specific AI agent.',
    args: {
      agentId: t.arg.string({ required: false }),
      limit: t.arg.int({ defaultValue: 100 }),
    },
    resolve: (_p, args) => {
      const violations = getWarrior().getScopeViolations(args.agentId ?? undefined);
      return violations.slice(0, args.limit ?? 100);
    },
  })
);

builder.queryField('generatedPolicies', (t) =>
  t.field({
    type: ['GeneratedPolicy'],
    description: 'Policies auto-generated by the warrior in response to attack chains.',
    args: {
      limit: t.arg.int({ defaultValue: 50 }),
      pendingApprovalOnly: t.arg.boolean({ defaultValue: false }),
    },
    resolve: (_p, args) => {
      const policies = getWarrior().getGeneratedPolicies();
      const filtered = (args.pendingApprovalOnly ?? false)
        ? policies.filter((p) => p.requiresApproval && !p.autoApplied)
        : policies;
      return filtered.slice(0, args.limit ?? 50);
    },
  })
);

builder.queryField('quarantinedAgents', (t) =>
  t.field({
    type: ['QuarantinedAgent'],
    description: 'All quarantined AI agents (active and released).',
    args: {
      activeOnly: t.arg.boolean({ defaultValue: true }),
    },
    resolve: (_p, args) => {
      const w = getWarrior();
      return (args.activeOnly ?? true)
        ? w.getActiveQuarantinedAgents()
        : w.getQuarantinedAgents();
    },
  })
);

builder.queryField('honeypotAssets', (t) =>
  t.field({
    type: ['HoneypotAsset'],
    description: 'All deployed honeypot decoy assets and their trigger state.',
    args: {
      triggeredOnly: t.arg.boolean({ defaultValue: false }),
    },
    resolve: (_p, args) => {
      const assets = getWarrior().honeypotManager.getAll();
      return (args.triggeredOnly ?? false)
        ? assets.filter((a) => a.triggered)
        : assets;
    },
  })
);

builder.queryField('warriorEvents', (t) =>
  t.field({
    type: ['WarriorEvent'],
    description: 'Recent in-memory warrior events (last 500) for polling.',
    args: {
      limit: t.arg.int({ defaultValue: 50 }),
      type: t.arg.string({ required: false }),
    },
    resolve: (_p, args) => {
      const events = getRecentEvents();
      const filtered = args.type
        ? events.filter((e) => e.type === args.type)
        : events;
      return filtered
        .slice(-(args.limit ?? 50))
        .reverse()
        .map((e) => ({ type: e.type, at: e.at }));
    },
  })
);

builder.queryField('incidentReport', (t) =>
  t.field({
    type: 'IncidentReport',
    nullable: true,
    description: 'Generate an on-demand LLM incident report covering the past N hours.',
    args: {
      hoursBack: t.arg.int({ defaultValue: 24 }),
    },
    resolve: async (_p, args) => {
      const now = new Date();
      const start = new Date(now.getTime() - (args.hoursBack ?? 24) * 3_600_000);
      return getWarrior().generateReport({ start, end: now });
    },
  })
);

// ─── Mutations ────────────────────────────────────────────────────────────────

builder.mutationField('releaseAgent', (t) =>
  t.field({
    type: 'Boolean',
    description: 'Release a quarantined AI agent from isolation.',
    args: {
      agentId: t.arg.string({ required: true }),
    },
    resolve: (_p, args) => {
      return getWarrior().releaseAgent(args.agentId);
    },
  })
);

builder.mutationField('applyPolicy', (t) =>
  t.field({
    type: 'Boolean',
    description: 'Mark a generated policy as manually applied (clears requiresApproval).',
    args: {
      policyId: t.arg.string({ required: true }),
    },
    resolve: (_p, args) => {
      return getWarrior().applyPolicy(args.policyId);
    },
  })
);

builder.mutationField('registerScopePreset', (t) =>
  t.field({
    type: 'Boolean',
    description: 'Register a built-in scope preset for a known AI agent.',
    args: {
      agentId: t.arg.string({ required: true }),
      agentName: t.arg.string({ required: true }),
      presetId: t.arg.string({ required: true }),
      workspaceRoot: t.arg.string({ required: false }),
    },
    resolve: (_p, args) => {
      const overrides = args.workspaceRoot
        ? { workspaceRoot: args.workspaceRoot }
        : undefined;
      getWarrior().registerPreset(args.agentId, args.agentName, args.presetId as any, overrides);
      return true;
    },
  })
);

builder.mutationField('ingestThreatEvent', (t) =>
  t.field({
    type: 'Boolean',
    description: 'Manually inject a threat event into the warrior pipeline (for testing / API integrations).',
    args: {
      source: t.arg.string({ required: true }),
      severity: t.arg.string({ required: true }),
      action: t.arg.string({ required: true }),
      resource: t.arg.string({ required: true }),
      agentId: t.arg.string({ required: false }),
      agentName: t.arg.string({ required: false }),
      byteCount: t.arg.int({ required: false }),
    },
    resolve: (_p, args) => {
      getWarrior().ingest({
        id: `manual-${Date.now()}`,
        timestamp: new Date(),
        source: args.source as ThreatSource,
        severity: args.severity as ThreatSeverity,
        action: args.action,
        resource: args.resource,
        agentId: args.agentId ?? undefined,
        agentName: args.agentName ?? undefined,
        byteCount: args.byteCount ?? undefined,
        metadata: { manual: true },
        isBlocked: false,
      });
      return true;
    },
  })
);

builder.mutationField('deployDefaultHoneypots', (t) =>
  t.field({
    type: 'Boolean',
    description: 'Deploy the default honeypot decoy files to the monitored directory.',
    resolve: async () => {
      await getWarrior().honeypotManager.deploy();
      return true;
    },
  })
);
